name: attendance_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  geolocator: ^10.1.0
  geocoding: ^4.0.0
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  iconsax: ^0.0.8
  glassmorphism_ui: ^0.3.0
  fl_chart: ^1.0.0
  animated_toggle_switch: ^0.8.5
  google_maps_flutter: ^2.12.3
  toggle_switch: ^2.3.0
  intl: ^0.20.2
  freezed: ^3.0.6
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_annotation: ^4.9.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

