// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBam_EuS5rGO4lqDQQRC1kY-69XD96MZC8',
    appId: '1:578425787362:web:5fa5c50bb7eb8485a4dfbb',
    messagingSenderId: '578425787362',
    projectId: 'attendence-app-63266',
    authDomain: 'attendence-app-63266.firebaseapp.com',
    storageBucket: 'attendence-app-63266.firebasestorage.app',
    measurementId: 'G-F3V68N2G7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqu_ProKuEf9CD0zwkq6pzAFBWdni-mZE',
    appId: '1:578425787362:android:877e14ca2e0653f5a4dfbb',
    messagingSenderId: '578425787362',
    projectId: 'attendence-app-63266',
    storageBucket: 'attendence-app-63266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVuo0i4KpeIS0wjaA7q88AbzebdrYDj8',
    appId: '1:578425787362:ios:afef449d297a8373a4dfbb',
    messagingSenderId: '578425787362',
    projectId: 'attendence-app-63266',
    storageBucket: 'attendence-app-63266.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );
}
